[package]
name = "wasmcloud-k8s-operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
roperator = "0.3.0"

[dev-dependencies]
roperator = { version = "0.3.0", features = ["testkit"] }
